### ISSUE TITLE
Raum Zustand im Frontend

### ISSUE THREAD

**Issue by FlorianRaith** [KIT-PSE/collab-space-frontend#46]
Werden im Frontend zu den Räume die Kategorien als Objekte oder als Zahlen (category id) gespeichert?

Egal wie rum, dass sollte vereinheitlich werden, am liebsten ist es mir wenn in den Räumen die Kategorien als Objekte gespeichert werden und nicht als Zahl. Falls ein Raum ausm Backend mit einer Zahl als Kategorie zurückgegeben wird, sollte das explizit angegeben werden mit einem anderem Return Type. (z.b. `someFunction(): Room & { category: number}`)

https://github.com/KIT-PSE/collab-space-frontend/commit/4f1b7838ae5b8a2e3e77a2706fc4f6a51ddcab7b#r123430415

**Comment by mariusfriess** [comment]
Naja ich glaube zu Beginn war es die ID und ich wollte es dann auch in das Category Objekt ändern aber das ist vielleicht doch nicht so optimal.

Im Store werden ja für den Nutzer die Category geladen und diese enthält Rooms. Anhand dessen werden die ja dann z.B. in der Room Component in der Übersicht angezeigt. Wenn man jetzt in dem Room die Category als Objekt darstellt wäre das ja ne gegenseitige Abhängigkeit. Deswegen vllt eher schauen, dass die Category in den Rooms überall als categoryId ist oder?

**Comment by FlorianRaith** [comment]
> Im Store werden ja für den Nutzer die Category geladen und diese enthält eine Liste an Rooms. Anhand dessen werden die ja dann z.B. in der Room Component in der Übersicht angezeigt. Wenn man jetzt in dem Room die Category als Objekt darstellt wäre das ja ne gegenseitige Abhängigkeit. Deswegen vllt eher schauen, dass die Category in den Rooms überall nur als categoryId ist oder?

Ja, dann machen wirs so. Also das Problem ist grade, dass laut dem Typ in `api.ts` `room.category` eine number sein soll, halt eben die id der Kategorie, aber teilweise eigtl ein `Category` object ist.

Das führt dazu, dass Typescript nicht rum meckert, wenn man z.b. `findCategory(room.category)` aufruft. findCategory erwartet eine number und laut Typescript ist `room.category` eine number, aber eigentlich wird da ein Objekt übergeben

**Comment by FlorianRaith** [comment]
@mariusfriess wie schauts hier mit aus? Das wäre schon etwas dringend

**Comment by mariusfriess** [comment]
Ja ich schaue das ichs heute noch mache. Basically überall wo im Backend ein einzelner Raum zurückgegeben wird, wird es wahrscheinlich falsch sein.

**Comment by FlorianRaith** [comment]
Ansonsten kann ichs mir grade anschauen, komme ansonsten nicht weiter, weil da ein paar Stellen kaputt deswegen sind
